

data = [ { "ID":12,
          "Name":"Jake",
          "Gender": "Male",
          "Age":30,
          "Ethnicity":"Caucasian",
          "Keywords":["break up", "depressed","debt"],
          "Location": { "Lat":40.7061, "Lon":-73.9969 },
         },
        { "ID":23,
          "Name":"Amy",
          "Gender": "Female",
          "Age":30,
          "Ethnicity":"Latino",
          "Keywords":["break up", "depressed","anxiety"],
          "Location": { "Lat":50.7061, "Lon":-53.8969 },
         },
        { "ID":33,
          "Name":"Charles",
          "Gender": "Male",
          "Age":30,
          "Ethnicity":"Italian",
          "Keywords":["broke","anxiety"],
          "Location": { "Lat":50.7061, "Lon":-53.9969 },
         },
        { "ID":43,
          "Name":"Rosa",
          "Gender": "Female",
          "Age":30,
          "Ethnicity":"Latino",
          "Keywords":["broke","anxiety"],
          "Location": { "Lat":50.7061, "Lon":-53.9969 },
         },
        { "ID":33,
          "Name":"Charles",
          "Gender": "Male",
          "Age":30,
          "Ethnicity":"Latino",
          "Keywords":["broke","anxiety"],
          "Location": { "Lat":50.7061, "Lon":-53.9969 },
         },
        { "ID":33,
          "Name":"Charles",
          "Gender": "Male",
          "Age":30,
          "Ethnicity":"Latino",
          "Keywords":["broke","anxiety"],
          "Location": { "Lat":50.7061, "Lon":-53.9969 },
         },
        { "ID":33,
          "Name":"Jessy",
          "Gender": "Female",
          "Age":18,
          "Ethnicity":"Chinese",
          "Keywords":["broke","alcoholic"],
          "Location": { "Lat":50.7061, "Lon":-53.9969 },
         }
      ]
        
  